### ISSUE TITLE
Assigning Component Field Layouts to Option Pages only works alphabetical order

### ISSUE THREAD

**Issue by bdbch** [flyntwp/flynt-starter-theme#155]
I tried to create an OptionPage in the Component `LayoutMultiplePosts` which contains a flexible content containing the Field Layouts

```
{
  "translatableOptions": [
    {
      "label": "Page Components",
      "name": "pageComponents",
      "type": "flexible_content",
      "button_label": "Add Component",
      "layouts": [
        "Flynt/Components/SectionContentColumns/Fields/Layout",
        "Flynt/Components/SectionContentSidebar/Fields/Layout",
        "Flynt/Components/SectionFullwidth/Fields/Layout"
      ]
    }
  ]
}
```

ACF currently doesn't know about the Field Layouts of the specified components, because the `LayoutMultiplePosts` comes first in alphabetical order.

That means, while loading the OptionPages for `LayoutMultiplePosts`, the Fields for every Component coming afterwards are not loaded and accessible.

Components coming before the letter L are working fine.

**Comment by Qakulukiam** [comment]
Will attempt to fix this after #166 and #167 are merged.

**Comment by Qakulukiam** [comment]
@bdbch could you check if #195 has fixed this issue for you?

**Comment by bdbch** [comment]
@Qakulukiam works now!
