### ISSUE TITLE
Posts password protection logic broken

### ISSUE THREAD

**Issue by vandebled** [flyntwp/flynt-starter-theme#200]
The archive page uses the `LayoutMultiplePosts` layout and the `ListsPosts` component.
https://github.com/flyntwp/flynt-starter-theme/blob/master/config/templates/archive.json

If the first post of my list is password protected, then the whole archive page shows the password protection form.
This is caused by the `LayoutMultiplePosts` component, in `functions.php` inside the `getPasswordContext`: the `$postId` is null, therefor the function `post_password_required` returns true because `$post = get_post($post);` with an null $post returns the first post of the page (my protected post)
https://developer.wordpress.org/reference/functions/post_password_required/

**Comment by Qakulukiam** [comment]
@vandebled was this fixed by #205 ?

**Comment by Qakulukiam** [comment]
True, I will leave it open then.
