### ISSUE TITLE
Utils should have DocBlocks

### ISSUE THREAD

**Issue by emcarru** [flyntwp/flynt-starter-theme#206]
The documentation team decided that each util function should be documented with a [DocBlock](https://phpdoc.org/docs/latest/references/phpdoc/basic-syntax.html), rather than in the documentation repo. I'd like to keep track of which Utils are done here.

- [x] [ArrayHelpers](https://github.com/flyntwp/flynt-starter-theme/blob/master/lib/Utils/ArrayHelpers.php)
- [x] [Asset](https://github.com/flyntwp/flynt-starter-theme/blob/master/lib/Utils/Asset.php)
- [x] [Feature](https://github.com/flyntwp/flynt-starter-theme/blob/master/lib/Utils/Feature.php)
- [x] [FileLoader](https://github.com/flyntwp/flynt-starter-theme/blob/master/lib/Utils/FileLoader.php)
- [x] [Log](https://github.com/flyntwp/flynt-starter-theme/blob/master/lib/Utils/Log.php)
- [x] [Oembed](https://github.com/flyntwp/flynt-starter-theme/blob/master/lib/Utils/Oembed.php)
- [x] [StringHelpers](https://github.com/flyntwp/flynt-starter-theme/blob/master/lib/Utils/StringHelpers.php)

**Comment by vandebled** [comment]
TimberHelper is removed

**Comment by emcarru** [comment]
OK thanks, I've removed it from the list.
