### ISSUE TITLE
Asset Util should have a way to get the contents of a file

### ISSUE THREAD

**Issue by emcarru** [flyntwp/flynt-starter-theme#216]
This is useful for SVGs. We added this on a few projects before. Is there a nicer way than this?

```php
  public static function getContents($asset) {
    $file = self::requirePath($asset);
    return (file_exists($file)) ? file_get_contents($file) : false;
  }
```

**Comment by Qakulukiam** [comment]
Only way to shorten this that I can think of is
```php
public static function getContents($asset) {
    $file = self::requirePath($asset);
    return @file_get_contents($file);
  }
```
Suppresses the file does not exist warning and still returns false. Not sure if there are other errors/warnings that shouldn't be suppressed though.
