### ISSUE TITLE
Clean up templates

### ISSUE THREAD

**Issue by domtra** [flyntwp/flynt-starter-theme#223]
The template files `templates/index.php`, `templates/page.php`, and `templates/single.php` all render the `default.json` page config. All but `index.php` can be removed.

Also, the `templates/archive.php` renders `archive-unfiltered.json`. This file does not exist.

**Comment by Qakulukiam** [comment]
I believe these files were left in here to make the usage of WordPress templates more obvious.

`archive.php` was fixed in https://github.com/flyntwp/flynt-starter-theme/commit/b4b3baaf8e2e8f7c3f39976f47c6d163c2bae673
