### ISSUE TITLE
Check requirements for ES6 polyfills

### ISSUE THREAD

**Issue by bdbch** [flyntwp/flynt-starter-theme#238]
We should check our requirements for the flynt-starter-theme again to see if we need any additional ES6 polyfills. (Promises, Object.assign, etc.).

There is `babel-polyfill` already included which states on the website that it brings support for ES6 builtins but we should make sure that ES6 functions are working in IEs.

**Comment by Qakulukiam** [comment]
Where is this coming from? Was there a bug at some point or missing functionality?

We're using https://babeljs.io/docs/plugins/preset-es2015/ to compile into ES5. If we ever find a reason to add another polyfill, I'd be happy to discuss. For now, without an actual need and / or bug report I'll close this ticket.
