### ISSUE TITLE
Clean Flynt install: standard post page doesn't displays the Wysiwyg content

### ISSUE THREAD

**Issue by Futos** [flyntwp/flynt-starter-theme#267]
Hey Guys

Thanks for improving Flynt day by day, it’s very nice to see progress here!. The Flynt snippets for example, saves me a lot of time. 👍

I came across with a problem. I created a new Flynt Project over the CLI like describes on the Getting started page. Then I added in the postComponents.json the following:

```
"layouts": [
   "Flynt/Components/BlockWysiwyg/Fields/Layout"
 ]
```

After that I created a new default Wordpress post with Wysiwyg content but it doesn’t shows the content from ACF Fields (the same with other components). Only the fresh default Hello World post from Wordpress is displayed correctly.

On other pages like for example the homepage everything works fine like expected.

**Environment:**
WordPress 4.9.4
ACF PRO Version 5.6.9 

**Way to Reproduce:**
1. Install fresh Flynt Project over CLI
2. Add to postComponents.json BlockWysiwyg component
3. Create a post with some content
4. Visit the post page

Thanks for your answers. 🙏

Cheers
Tobias

**Comment by Qakulukiam** [comment]
Hey @Futos,

It sounds to me like you are missing a step. Here are a few things you can check:

- did you run `flynt start` or `flynt build`?
- did you add the correct WordPress template in the templates directory and did you make sure the correct config is being loaded in that template? (more info here: https://docs.flyntwp.com/guide/configuration/page-templates/) -> **you need to add a single.php and a config file (single.json for example) with the fieldGroup "postComponents" selected (the default.json uses "pageComponents").**

Let me know if that helped resolve your issue.

**Comment by Futos** [comment]
Hey @Qakulukiam,

Thanks for your help, I managed to resolve my issue. ;)
