### ISSUE TITLE
Idea: Switch to Vue instead of jQuery

### ISSUE THREAD

**Issue by bdbch** [flyntwp/flynt-starter-theme#272]
This is just an idea I picked up a few times while working with flynt and tried it out once.

Since jQuery is larger than Vue and can be kind of annoying to work with and Vue being very flexible also with pre-rendered content it could be a viable solution for the flynt-starter-theme in general. With custom-elements it's super easy anyway since you can just use the custom-elements `this` as the element for a new Vue instance.

I liked working with Vue in Flynt and maybe it's a thought you guys also find interesting!

**Comment by Qakulukiam** [comment]
Hey @bdbch,

interesting idea. However, we are not currently looking to add another big default dependency to the Flynt stack that devs would have to learn first. One of Flynt's biggest features is that it is flexible enough to be used with any additional framework if you want to (as you've done).

Additionally, with jQuery being a default WordPress dependency that many plugins rely on, we would keep this around for now.

**Comment by bdbch** [comment]
Thats true, didn't thought about the core dependencies of WP. Thanks for the feedback.
